[package]
name = "riscv-qemu-guest"
version = "0.1.0"
edition = "2021"

[dependencies]
fdt = "0.1.3"
panic-halt = "0.2.0"
riscv-rt = "0.8.1"

[[bin]]
name = "guest"
path = "src/main.rs"
harness = false
