[profile.release]
opt-level = "s"

[build]
target = "riscv32i-unknown-none-elf"

[target.riscv32i-unknown-none-elf]
rustflags = ["-C", "link-arg=-Tmemory.x", "-C", "link-arg=-Tlink.x"]
runner = "qemu-system-riscv32 -machine virt -m 128 -device ramfb -serial stdio -bios none -kernel"
